language: php

sudo: false

php:
  - 7.1
  - 7.2

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-dist

script:
  - ./vendor/bin/phpcs ./ -p --encoding=utf-8 --extensions=php --ignore="vendor|Tests" --standard=./vendor/escapestudios/symfony2-coding-standard/Symfony
  - ./vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=coverage.xml
  - ./vendor/bin/phpstan analyse -l 7 --no-progress -c phpstan.neon ./

cache:
  directories:
    - $COMPOSER_CACHE_DIR

notifications:
  email: false
